Fixed dupe bug with Essentia condenser
GTNewHorizons/Gadomancy pull request #27
Opened 2023-12-13 20:36 UTC by OneEyeMaker

This PR changes logic of Essentia condenser to allow access to essentia *only* using central block of multiblock.
Fixes dupe bug with bus from Thaumic Energistics attached to energy condenser.
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10522
Complex testing is necessary.

2023-12-13 20:59 UTC, chochem commented
this goes together with https://github.com/GTNewHorizons/MagicBees/pull/34, so its frozen until after stable

2023-12-14 02:35 UTC, Alastors commented
<img width="1440" alt="Screen_Shot_2023-12-13_at_9 16 42_PM" src="https://github.com/GTNewHorizons/Gadomancy/assets/78517796/dadef72e-6ebc-484d-b7a0-aa224beb90de">
<img width="500" alt="Screen_Shot_2023-12-13_at_9 17 24_PM" src="https://github.com/GTNewHorizons/Gadomancy/assets/78517796/3ba68649-d85d-47fb-8f4f-5ecfcd70df46">
<img width="288" alt="Screen_Shot_2023-12-13_at_9 17 33_PM" src="https://github.com/GTNewHorizons/Gadomancy/assets/78517796/3803fa83-a17d-4d75-86fe-d3d1362e0f8f">
<img width="1440" alt="Screen_Shot_2023-12-13_at_9 19 24_PM" src="https://github.com/GTNewHorizons/Gadomancy/assets/78517796/af80c7cb-9c98-4f7c-a5ac-6272459b677a">

This fixes the dupe ***when you only use the storage bus*** but it introduces a new dupe, that being:

when you insert essentia into the condenser from AE it doesn't actually take the essentia from AE now, it did take it from it formerly when actually inserted directly into the condenser, instead of jars.

I originally believed this was two separate bugs, however, I figured out that the 64 cap was only some terrible coding in TE that will need to be fixed on a later date, however, yes, the original dupe was fixed in this.

2023-12-14 02:36 UTC, Alastors requested changes
Introduces a new dupe

2023-12-14 09:07 UTC, OneEyeMaker commented
I fixed issue with essentia insertion. And found another one: Essentia condenser cannot be filled more then with 64 essentia from ME system. That's issue of Thaumic Energistics. ThE hardcodes capacity of condenser to be equal 64 (because Thaumcraft API provides no ways to get capacity of `IAspectContainer`).
So I'm going to create PR to that mod to fix this part of issue.

2023-12-20 19:35 UTC, Alastors approved these changes
Fixed the dupe, couldn't find any new issues in my testing, seems good

2023-12-22 18:46 UTC, OneEyeMaker commented
Now this fix is finished. Essentia condenser should properly work with ThE and other accessors and provide full its capacity.

2023-12-22 21:43 UTC, TechnicianLP approved these changes
Looks fine.
This class should really be split into 2-3 classes as access/master/plain are quite different and just blended together here.

2023-12-22 21:53 UTC, merged